language: python
python:
    - "3.6"
install:
    - pip install .[test]
# command to run tests
script:
    - pytest

deploy:
    provider: pypi
    user: $PYPI_USER
    password:
        secure: $PYPI_PASSWORD
    on:
        branch: master
        tag: true
